language: php
php:
- 5.3
env:
- DB=mysql
before_script:
- echo "test message"
script: echo "test message 2"
deploy:
  provider: s3
  access_key_id: AKIAILHE4W3F4FJZQBXA
  secret_access_key:
    secure: L7ReHmjjWdaW68R5QZWhF7awltLspWPCeztQUItdDKbBGKECg03KZxNNPRdcYex5HSmygrS4BbPikNmceQ8fE/qKrdSLb6Fkshje8i3MHGCIpNWZ4xipJP3lExJ9dF+/VGU9qKAgra2njh0WT4oRJWbLhXUqB0lsX2CrgznaLms=
  bucket: vikram-test
  on:
    repo: vikramnc/wordpress
